### ISSUE TITLE
After hugo migration: wrong branch published

### ISSUE THREAD

**Issue by kreczko** [SWIFT-HEP/swift-hep.github.io#9]
@davidecostanzo There is one change needed to complete the migration to hugo:
Change `main` under

![image](https://user-images.githubusercontent.com/1213276/151547862-cc61ffba-9ffe-4d38-b573-dbde5dda2c58.png)
(example from different repo as I have no permissions for this one)

to `gh-pages`.

See docs: https://gohugo.io/hosting-and-deployment/hosting-on-github/#github-pages-setting

**Comment by davidecostanzo** [comment]
Hi @kreczko 
    I don't have a "Setting" button on the main repository. I can see that menu in my fork. 

I think it's @drbenmorgan who has the privileges to change that.
Cheers
Davide

**Comment by davidecostanzo** [comment]
It works in my fork if I select "gh-pages" as a branch

https://davidecostanzo.github.io/swift-hep.github.io/

**Comment by kreczko** [comment]
It seems we need more members with higher permissions ;)

**Comment by drbenmorgan** [comment]
Done! I've also added @davidecostanzo and @kreczko as admins we've got more coverage here.
